// <auto-generated />
using FatecSisMed.MedicoAPI.Context.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FatecSisMed.MedicoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240513224631_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FatecSisMed.MedicoAPI.Model.Entities.Convenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Convenios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ben Saude"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Unimed"
                        });
                });

            modelBuilder.Entity("FatecSisMed.MedicoAPI.Model.Entities.Especialidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ortopedista"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Clínico Geral"
                        });
                });

            modelBuilder.Entity("FatecSisMed.MedicoAPI.Model.Entities.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CRM")
                        .HasColumnType("int");

                    b.Property<int>("ConvenioId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CRM = 123456,
                            ConvenioId = 1,
                            Email = "carlos@medico.com",
                            Endereco = "Av Joao Amadeu, 123, Jales",
                            EspecialidadeId = 1,
                            Nome = "Carlos",
                            Telefone = "17-12345678"
                        },
                        new
                        {
                            Id = 2,
                            CRM = 234567,
                            ConvenioId = 2,
                            Email = "filisbino@medico.com",
                            Endereco = "Av Joao Amadeu, 125, Jales",
                            EspecialidadeId = 2,
                            Nome = "Filisbino",
                            Telefone = "17-12345678"
                        });
                });

            modelBuilder.Entity("FatecSisMed.MedicoAPI.Model.Entities.Medico", b =>
                {
                    b.HasOne("FatecSisMed.MedicoAPI.Model.Entities.Convenio", "Convenio")
                        .WithMany("Medicos")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FatecSisMed.MedicoAPI.Model.Entities.Especialidade", "Especialidade")
                        .WithMany("Medicos")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("FatecSisMed.MedicoAPI.Model.Entities.Convenio", b =>
                {
                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("FatecSisMed.MedicoAPI.Model.Entities.Especialidade", b =>
                {
                    b.Navigation("Medicos");
                });
#pragma warning restore 612, 618
        }
    }
}
